---
on:
  label:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "something happened with labels"

---
on:
  issues:
    types:
      - opened
      - labeled
  page_build: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "something happened with issue labels and page build"
