---
on:
  release:
    types: [created]
jobs:
  on-release-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: jq '.' $GITHUB_EVENT_PATH
      - run: echo "release created"
